### ISSUE TITLE
NotImplementedError: Cannot fill along a chunked axis when limit is not None

### ISSUE THREAD

**Issue by eugene-tam-dpie** [coecms/era5grib#3]
Hi,

So I have been running multiple instances era5grib on small chunks of time periods (~6-7 days each run) and I suspect the following maybe due to this.
 
I am getting the following traceback at random time periods...
```
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-21.04/bin/era5grib", line 10, in <module>
    sys.exit(main())
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/era5grib/era5grib.py", line 285, in main
    func(**dargs)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/era5grib/era5grib.py", line 156, in era5grib_wrf
    ds = nci.read_wrf(start, end)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/era5grib/nci.py", line 248, in read_wrf
    ds = read_era5(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/era5grib/nci.py", line 206, in read_era5
    result.append(read_era5_month(surface_vars, pressure_vars, t.year, t.month))
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/era5grib/nci.py", line 186, in read_era5_month
    surf = [merged_land_surf(v, year, month) for v in surface_vars]
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/era5grib/nci.py", line 186, in <listcomp>
    surf = [merged_land_surf(v, year, month) for v in surface_vars]
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/era5grib/nci.py", line 172, in merged_land_surf
    land = land.bfill('time', limit=1)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/dataarray.py", line 2570, in bfill
    return bfill(self, dim, limit=limit)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/missing.py", line 430, in bfill
    return apply_ufunc(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/computation.py", line 1171, in apply_ufunc
    return apply_dataarray_vfunc(
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/computation.py", line 288, in apply_dataarray_vfunc
    result_var = func(*data_vars)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/computation.py", line 739, in apply_variable_ufunc
    result_data = func(*input_data)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/missing.py", line 400, in _bfill
    arr = push(arr, axis=axis, n=n)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/duck_array_ops.py", line 663, in push
    return dask_array_ops.push(array, n, axis)
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-21.04/lib/python3.8/site-packages/xarray/core/dask_array_ops.py", line 63, in push
    raise NotImplementedError(
NotImplementedError: Cannot fill along a chunked axis when limit is not None.Either rechunk to a single chunk along this axis or call .compute() or .load() first.
```

The reason to break the time into such small pieces is because we intend to run WRF in chunks of the same size and the script generating the timestamps are the same...

Is there any reason why limit cannot equal None in line 172 of nci.py?

**Comment by ScottWales** [comment]
Can you please tell me the dates that are causing this issue

**Comment by eugene-tam-dpie** [comment]
May not so random... all in Jan 1981
(1981-01-07 00:00:00:1981-01-12 23:00:00)
(1981-01-13 00:00:00:1981-01-18 23:00:00)
(1981-01-19 00:00:00:1981-01-24 23:00:00)
(1981-01-25 00:00:00:1981-01-30 23:00:00)

**Comment by eugene-tam-dpie** [comment]
In case it is useful below are sample namelists and pbs scripts used

Example namelist
```fortran
&share
 wrf_core = 'ARW',
 max_dom = 2,
 start_date = '1981-01-07_00:00:00', '1981-01-07_00:00:00',
 end_date   = '1981-01-12_23:00:00', '1981-01-12_23:00:00',
 interval_seconds = 3600,
 io_form_geogrid = 2,
 debug_level= 0,
/

&geogrid
 parent_id = 1, 1,
 parent_grid_ratio = 1, 5,
 i_parent_start = 1, 205,
 j_parent_start = 1, 90,
 e_we = 540, 616,
 e_sn = 363, 501,
 geog_data_res = 'default', 'default',
 dx = 0.176,
 dy = 0.176,
 map_proj = 'lat-lon',
 ref_lat = -24.26,
 ref_lon = 147.63,
 pole_lat = 60.31,
 pole_lon = 321.38,
 stand_lon = 32.37,
 geog_data_path = '/g/data/sx70/data/WPS_GEOG_v4',
/

&ungrib
 out_format = 'WPS',
 prefix = 'INVAR',
/

&metgrid
 constants_name = 'INV:1989-01-01_12',
 fg_name = 'INVAR',
 io_form_metgrid = 2,
/
```

Relevant parts of PBS script
```bash
#!/usr/bin/env bash
#PBS -P <project_code>
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -l ncpus=48
#PBS -l mem=192GB
#PBS -l jobfs=400GB
#PBS -lstorage=<project_code_storage>+gdata/hh5+gdata/sx70+gdata/rt52+gdata/zz93
#PBS -j oe
#PBS -l wd

set -e
module purge
module use /g/data/hh5/public/modules
module load conda/analysis3-unstable

era5grib wrf --namelist <namelist_directory>/namelist_1981_000.wps --geo <geo_em_directory>/geo_em.d01.nc --output <output_directory>/gribfile_1981_000.grib
```

**Comment by ScottWales** [comment]
Thanks, I've reproduced the error in the analysis3 environment

**Comment by ScottWales** [comment]
This should now be fixed. Seems to be taking more memory to process now though, you may need to use the queue if you're not doing so already.

**Comment by eugene-tam-dpie** [comment]
Cheers!
Tested same period with no issues
